// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/genricoloni/synest/internal/monitor (interfaces: DBusClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/dbus_client_mock.go -package=mocks github.com/genricoloni/synest/internal/monitor DBusClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dbus "github.com/godbus/dbus/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockDBusClient is a mock of DBusClient interface.
type MockDBusClient struct {
	ctrl     *gomock.Controller
	recorder *MockDBusClientMockRecorder
	isgomock struct{}
}

// MockDBusClientMockRecorder is the mock recorder for MockDBusClient.
type MockDBusClientMockRecorder struct {
	mock *MockDBusClient
}

// NewMockDBusClient creates a new mock instance.
func NewMockDBusClient(ctrl *gomock.Controller) *MockDBusClient {
	mock := &MockDBusClient{ctrl: ctrl}
	mock.recorder = &MockDBusClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBusClient) EXPECT() *MockDBusClientMockRecorder {
	return m.recorder
}

// AddMatchSignal mocks base method.
func (m *MockDBusClient) AddMatchSignal(options ...dbus.MatchOption) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddMatchSignal", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMatchSignal indicates an expected call of AddMatchSignal.
func (mr *MockDBusClientMockRecorder) AddMatchSignal(options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMatchSignal", reflect.TypeOf((*MockDBusClient)(nil).AddMatchSignal), options...)
}

// Close mocks base method.
func (m *MockDBusClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDBusClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDBusClient)(nil).Close))
}

// GetNameOwner mocks base method.
func (m *MockDBusClient) GetNameOwner(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNameOwner", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNameOwner indicates an expected call of GetNameOwner.
func (mr *MockDBusClientMockRecorder) GetNameOwner(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNameOwner", reflect.TypeOf((*MockDBusClient)(nil).GetNameOwner), name)
}

// GetProperty mocks base method.
func (m *MockDBusClient) GetProperty(player, path, prop string) (dbus.Variant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProperty", player, path, prop)
	ret0, _ := ret[0].(dbus.Variant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProperty indicates an expected call of GetProperty.
func (mr *MockDBusClientMockRecorder) GetProperty(player, path, prop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProperty", reflect.TypeOf((*MockDBusClient)(nil).GetProperty), player, path, prop)
}

// ListNames mocks base method.
func (m *MockDBusClient) ListNames() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNames")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNames indicates an expected call of ListNames.
func (mr *MockDBusClientMockRecorder) ListNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNames", reflect.TypeOf((*MockDBusClient)(nil).ListNames))
}

// Signal mocks base method.
func (m *MockDBusClient) Signal(ch chan<- *dbus.Signal) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Signal", ch)
}

// Signal indicates an expected call of Signal.
func (mr *MockDBusClientMockRecorder) Signal(ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockDBusClient)(nil).Signal), ch)
}
